---
config:
  theme: neo-dark
  layout: elk
---
flowchart TD
 subgraph client_side["Client Side"]
        Client(("Client"))
  end
 subgraph auth_service["Auth Service"]
        Auth["Auth Service - FastAPI"]
        DB["PostgreSQL - RDS"]
        JWT["JWT / Email verification"]
  end
 subgraph monitoring["Monitoring"]
        Loki["Loki"]
        Prom["Prometheus"]
        Grafana["Grafana"]
  end
 subgraph microservices["Microservices"]
        TemplateSvc["Template Service Demo"]
        UsersAPI["Users API - Scaffold Service"]
        PaymentsAPI["Payments API"]
        More("Adittional Services")
  end
    Auth --> DB
    Auth -. internal .- JWT
    Prom --> Grafana
    Client L_Client_Auth_0@-.-> Auth
    Client L_Client_TemplateSvc_0@--> TemplateSvc
    Auth -- "Logs JSON - Loguru" --> Loki
    Auth -- Metrics /metrics --> Prom
    TemplateSvc --> UsersAPI & PaymentsAPI
    TemplateSvc -. scale out .-> More
    style Client stroke-width:4px,stroke-dasharray: 0
    L_Client_Auth_0@{ animation: slow } 
    L_Client_TemplateSvc_0@{ animation: slow }
