---
config:
  theme: neo-dark
  layout: elk
---
flowchart TD
 subgraph Alembic["Migrations (Alembic)"]
        versions["Versions"]
        env_template["env-template.py"]
  end
 subgraph k8s_dev["dev-k8s"]
        deploy(["deployment.yaml"])
        service(["service.yaml"])
        serviceAcc(["serviceAccount.yaml"])
        namespace(["namespace-dev.yaml"])
  end
 subgraph db_dev["dev-database"]
        secret(["secret.yaml.template"])
        servicedb(["service.yaml"])
        statefulSet(["statefulSet.yaml"])
  end
 subgraph K8sDev["Kubernetes (Dev)"]
        k8s_dev
        db_dev
  end
 subgraph Infra["Infrastructure"]
        K8sDev
  end
 subgraph Source["Source Code"]
        main["main.py"]
        auth["auth.py"]
        db["database.py"]
        models["models.py"]
        schemas["schemas.py"]
        utils["utils.py"]
  end
 subgraph Tests["Tests"]
        conftest["conftest.py"]
        endpoints["test_endpoints.py"]
  end
 subgraph AuthService["Auth Service (FastAPI + PostgreSQL)"]
        Alembic
        Infra
        Source
        Tests
  end
    Source --> Alembic & Infra & Tests
    Infra --> K8sDev
