---
config:
  theme: neo-dark
  layout: elk
---
flowchart TD
 subgraph CI["Continuous Integration"]
        checkout["Checkout Repository"]
        setup_python["Setup Python 3.11"]
        install_deps["Install dependencies - auth_service & users-api"]
        lint["Lint all services - flake8"]
        wait_pg["Wait for PostgreSQL readiness"]
        run_tests["Run tests with pytest"]
        build_docker["Build Docker images - local"]
  end
 subgraph CD["Continuous Deployment manual"]
        checkout_cd["Checkout Repository"]
        aws_login["Configure AWS credentials"]
        docker_login["Login to Docker Hub"]
        build_push["Build & Push Docker images"]
        terraform_apply["Terraform Init & Apply"]
  end
    CI/CD["CI/CD Pipeline (GitHub Actions)"] --> CD & CI
    checkout --o setup_python
    setup_python --o install_deps
    install_deps --o lint
    lint --o wait_pg
    wait_pg --o run_tests
    run_tests --o build_docker
    checkout_cd --o aws_login
    aws_login --o docker_login
    docker_login --o build_push
    build_push --o terraform_apply
