---
config:
  theme: neo-dark
---
flowchart TD
    subgraph Users_Api: Demo Microservice
        deployment_users[users-api-deployment.yaml]
        service_users[users-api-service.yaml]
        main_user[main.py]
        init_user[__init__.py]
        test_health[test_health.py]
        dockerfile[Dockerfile]
        requirements_user[requirements.txt]
    end
