---
config:
  theme: neo-dark
  layout: elk
---
flowchart TD
    Client["User / Client App"] L_Client_PCS_0@-- "POST /check-password<br>Bearer token" --> PCS["Password Checker Service<br>FastAPI + k-Anonymity"]
    PCS L_PCS_Auth_0@-- Validate token<br>/users/me --> Auth["Auth Service<br>FastAPI + JWT + PostgreSQL"]
    Auth --> Postgres[("PostgreSQL<br>User DB")] & Prometheus["Prometheus<br>Metrics"] & Loki["Loki<br>Structured Logs"]
    PCS L_PCS_HIBP_0@-- Query prefix hash --> HIBP["Have I Been Pwned API<br> - k-Anonymity"]
    PCS L_PCS_Prometheus_0@--> Prometheus & Loki
    Prometheus --> Grafana["Grafana Dashboards"]
    Loki --> Grafana
     PCS:::service
     Auth:::service
     Postgres:::db
     Prometheus:::observ
     Loki:::observ
     HIBP:::api
     Grafana:::observ
    classDef service fill:,stroke:#,stroke-width:1px
    classDef db fill:,stroke:#,stroke-width:1px
    classDef api fill:,stroke:#,stroke-width:1px
    classDef observ fill:,stroke:#,stroke-width:1px
    L_Client_PCS_0@{ animation: slow } 
    L_PCS_Auth_0@{ animation: slow } 
    L_PCS_HIBP_0@{ animation: slow } 
    L_PCS_Prometheus_0@{ animation: slow } 
    L_PCS_Loki_0@{ animation: slow }