---
config:
  theme: neo-dark
  layout: elk
---
flowchart LR
    A["leakguard"] --> B["auth_service"] & C["password_checker_service"] & D[".github"]
    B --> B1["src"] & B2["requirements.txt"]
    C --> C1["src_pcs"] & C2["requirements.txt"] & C3["tests"] & C4["test_auth.py"] & C5["test_password_checker.py"]
    D --> D1["workflows"]
    D1 --> D2["ci-cd-dev.yaml"]
