```mermaid
flowchart TD
    cloud[Cloud Microservices]
    cloud --> github[.github]
    cloud --> auth_service[auth_service]
    cloud --> monitoring[monitoring]
    cloud --> terraform[terraform]
    cloud --> user_api[user_api]
    cloud --> gitignore[.gitignore]