---
config:
  theme: neo-dark
---
flowchart TD
    subgraph Terraform: IaC
        terraform_lock[.terraform.lock.hcl]
        main_tf[main.tf]
        outputs_tf[outputs.tf]
        tfvars_example[terraform.tfvars.example]
    end
