apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-prod
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - name: metrics
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
