apiVersion: v1
kind: Service
metadata:
  name: password-checker
  namespace: auth-dev
  labels:
    app: password-checker
spec:
  selector:
    app: password-checker
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
