apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-sa
      containers:
        - name: auth-container
          image: gilbr/auth-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: ENVIRONMENT
              value: production
            - name: AWS_REGION
              value: us-west-2
            - name: AWS_SECRET_NAME
              value: <AWS_SECRET_NAME_PLACEHOLDER>
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
