name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2

    steps:
      #Checkout from repo
      - name: Checkout repository
        uses: actions/checkout@v3

      #Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      #Configure Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      #Install dependencies
      - name: Install dependencies
        run: |
          pip install -r auth-service/requirements.txt
          pip install -r users-api/requirements.txt
          pip install flake8 pytest mypy

      #Code Validation
      - name: Lint auth-service
        run: flake8 auth-service/src
      - name: Lint users-api
        run: flake8 users-api/src
      - name: Run tests auth-service
        run: pytest auth-service/tests
      - name: Run tests users-api
        run: pytest users-api/tests

      #Build Docker images
      - name: Build auth-service image
        run: docker build -t gilbr/auth-service:latest auth-service/
      - name: Build users-api image
        run: docker build -t gilbr/users-api:latest users-api/

      #Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #Push Docker images
      - name: Push auth-service image
        run: docker push gilbr/auth-service:latest
      - name: Push users-api image
        run: docker push gilbr/users-api:latest

      #Define namespace according to branch'
      - name: Set namespace
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "NAMESPACE=auth-prod" >> $GITHUB_ENV
          else
            echo "NAMESPACE=auth-dev" >> $GITHUB_ENV
          fi

      #Replace placeholders and deploy auth-service
      - name: Deploy auth-service
        run: |
          mkdir -p auth-service/infra/k8s/${{ env.NAMESPACE }}
          sed "s|<IAM_ROLE_ARN_PLACEHOLDER>|${{ secrets.IAM_ROLE_ARN }}|g" \
           auth-service/infra/k8s/templates/serviceAccount-prod-template.yaml \
           > auth-service/infra/k8s/${{ env.NAMESPACE }}/serviceAccount-prod.yaml

          sed "s|<AWS_SECRET_NAME_PLACEHOLDER>|${{ secrets.AWS_SECRET_NAME }}|g" \
            auth-service/infra/k8s/templates/deployment-prod-template.yaml \
            > auth-service/infra/k8s/${{ env.NAMESPACE }}/deployment-prod.yaml

        #  kubectl apply -f auth-service/infra/k8s/${{ env.NAMESPACE }}/ --validate=false

      #Deploy monitoring stack (Grafana, Prometheus, Loki)/// 
      - name: Deploy monitoring stack
        run: |
          for service in grafana prometheus loki; do
            kubectl apply -f infra/k8s/monitoring/$service/
          done
